#' create a neural networks to assign to a cluster an out-of-sample observation
#'
#' @param cluster_object  an object generated by create_cluster_object function
#' @param chosen_id       character: the id_key from the cluster_object output. if NULL, choose the max(silhouette)
#' @param suffix_transf   character: the suffix at variables name to indicate it was transformed and to use original variable (easier to deploy on out-of-sample)
#'
#' @return a neural networks object
#'
#' @export
classify_cluster <- function(cluster_object, chosen_id = NULL, suffix_transf = NULL) {
  # chosen_id
  if (is.null(chosen_id)) {
    chosen_id <- cluster_object$cluster %>%
      arrange(desc(mean_silh)) %>%
      slice(1) %>%
      pull(id_key)
  }
  # suffix_transf
  if (is.null(suffix_transf)) {
    suffix_transf <- '_transf'
  }

  # get variable names
  variables_nnet <- cluster_object$cluster %>%
    filter(id_key == chosen_id) %>%
    pull(variables) %>% unlist() %>%
    gsub(pattern = suffix_transf, replacement = '', x = .)

  # generate data.frame for nnet
  df_nnet <- tibble(
    cluster_object$original_df %>% select(all_of(variables_nnet)),
    Cluster = {cluster_object$cluster %>%
        filter(id_key == chosen_id) %>%
        pull(cluster) %>% unlist()}
  ) %>%
    mutate(Cluster = paste('c_', Cluster, sep = "")) %>%
    mutate(Cluster = as_factor(Cluster))

  # train a neural network to evaluate
  model_nnet <- nnet::nnet.formula(Cluster ~ .,
                                      size = 10,
                                      data = df_nnet,
                                      trace = FALSE)
return(model_nnet)
}
