# library(party)
# library(tidyverse)
# library(shiny)
# library(plotly)
# library(DT)
# library(shinydashboard)

#' create a shiny app for interactive visualization of clusters
#'
#' @param cluster_object  an object generated by create_cluster_object function
#' @param screen_height   character: the height of the screen in pixels. example: '640px'
#' @param suffix_transf   character: the suffix at variables name to indicate it was transformed and to use original variable at tree plot(if null, it is set to _transf).
#'
#' @return a shiny app object
#'
#' @export
create_cluster_app <- function(cluster_object, screen_height = '900px',
                               suffix_transf = NULL) {
  #
  if (is.null(suffix_transf)) {
    suffix_transf <- '_transf'
  }

  # create inputs: available clusters
  available_clusters <- clusters_obj$cluster$id_key
  names(available_clusters) <- available_clusters

  # create inputs: numeric variables
  numeric_variables <- clusters_obj$original_df %>%
    select(where(is.numeric)) %>%
    colnames()
  names(numeric_variables) <- numeric_variables

  # create app object
  app <- shinyApp(
    # UI ----
    ui = dashboardPage(
      skin = "blue",
      # # UI: CABEÇALHO ----
      dashboardHeader(title = 'Cluster'),
      # # UI: BARRA LATERAL ----
      dashboardSidebar(width = 300,
                       sidebarMenu(
                         tags$hr("Candidates Comparison"),
                         menuItem("Summary of the Candidates", tabName = "sumarioCandidatos", icon = icon("info"), selected = TRUE),

                         tags$hr(" Selected Cluster Visualization"),

                         menuItem("Summary Table", tabName = "tabNaoPar", icon = icon("table")),
                         menuItem("Plot by Observations", tabName = "plotClnt", icon = icon("chart-bar")),
                         menuItem("Plot by Clusters", tabName = "plotClst", icon = icon("chart-line")),
                         menuItem("Cluster Decision Tree", tabName = "arvoreCluster", icon = icon("chart-bar")),

                         tags$hr(" Filters"),

                         menuItem(
                           "Select Cluster", tabName = "selecaoCamp", icon = icon("filter"),
                           selectInput(inputId = "cluster", label = "Cluster:",
                                       choices = available_clusters, selected = names(available_clusters)[1])
                         ),
                         menuItem(
                           #startExpanded = TRUE,
                           "Filters for Observations", tabName = "selecaoPlotCliente", icon = icon("filter"),
                           selectInput(inputId = "varPlotX", label = "observation x-axis:", choices = numeric_variables, selected = numeric_variables[length(numeric_variables) - 1]),
                           selectInput(inputId = "varPlotY", label = "observation y-axis:", choices = numeric_variables, selected = numeric_variables[length(numeric_variables) - 2]),
                           selectInput(inputId = "varPlotZ", label = "observation z-axis:", choices = numeric_variables, selected = numeric_variables[length(numeric_variables) - 3])
                         ),
                         menuItem(
                           "Filters for Cluster", tabName = "selecaoPlotCluster", icon = icon("filter"),
                           selectInput(inputId = "varPlotBox", label = "Box Plot Variable:", choices = numeric_variables,selected = numeric_variables[1]),
                           selectInput(inputId = "clusterX", label = "cluster x-axis:", choices = numeric_variables, selected = numeric_variables[length(numeric_variables) - 1]),
                           selectInput(inputId = "clusterY", label = "cluster y-axis:", choices = numeric_variables, selected = numeric_variables[length(numeric_variables) - 2]),
                           selectInput(inputId = "clusterZ", label = "cluster z-axis:", choices = numeric_variables, selected = numeric_variables[length(numeric_variables) - 3])
                         )
                       )
      ),
      # # UI: CORPO ----
      dashboardBody(
        tabItems(
          # # # UI: CORPO: SUMARIO CANDIDATOS ----
          tabItem(tabName = 'sumarioCandidatos',
                  fluidRow(
                    box(title = "Candidate Clusters Comparison", width = 8,
                        fluidRow(plotlyOutput("plotSil"))
                    ),
                    box(title = "Frequency Varaibles (selected clusters)", width = 4,
                        fluidRow(DT::dataTableOutput("dfMelhores"), width = 12)
                    ),
                    box(title = "Summary Table", width = 12,
                        fluidRow(DT::dataTableOutput("dfSumario"), width = 12)
                    )
                  )
          ),
          # # # UI: CORPO: TABELA NÃO-PARAMÉTRICA ----
          tabItem(tabName = 'tabNaoPar',
                  # fluidRow(
                  #   box(title = "Tabela Dados Não-Paramétricos", width = 12,
                  #       fluidRow(dataTableOutput("dfNaoParm"))
                  #   )
                  # )
                  fluidRow(dataTableOutput("dfNaoParm"))
          ),
          # # # UI: CORPO: GRÁFICO CLIENTE -----
          tabItem(tabName = 'plotClnt',
                  fluidRow(
                    box(title = "3D-scatter for observations", width = 12,
                        fluidRow(plotlyOutput("plotCluster"))
                    ),
                    box(title = "Summary Table of selected variables", width = 12,
                        fluidRow(dataTableOutput("dfNpPorCliente"))
                    )
                  )
          ),
          # # # UI: CORPO: GRÁFICOS CLUSTER -----
          tabItem(tabName = 'plotClst',
                  fluidRow(
                    box(title = "3D-scatter for cluster", width = 12,
                        fluidRow(plotlyOutput("plotPorCluster"))
                    ),
                    box(title = "Box-Plot for cluster", width = 12,
                        fluidRow(plotlyOutput("plotBox"), width = 12)
                    )
                  )
          ),
          # # # UI: CORPO: ÁRVORE DECISÃO ----
          tabItem(tabName = 'arvoreCluster',
                  fluidPage(plotOutput('tree_plot', height = screen_height, width = "100%"))
          )
          #
        )
      )
    ),

    # SERVER ----
    server = function(input, output) {
      # # REACTIVE: ----
          # # # (AJUSTADO-OK) REACTIVE: DF NÃO-PARAMÉTRICA ----
      dfNaoParm <- reactive({
        # select the data
        df_summary_all_variables <- tibble(cluster_object$original_df,
                                           Cluster = {cluster_object$cluster %>%
                                               filter(id_key == input$cluster) %>%
                                               pull(cluster) %>% unlist()}) %>%
          mutate(Cluster = paste('cluster_', Cluster, sep = ""))

        # summarise
        app_helper_summary_table(df_tbl = df_summary_all_variables,
                                 grp = 'Cluster')

      })

          # # # (AJUSTADO-OK) REACTIVE: SCATTER 3D ----
      plotCluster <- reactive({
        # select the data
        df_plot_scatter_observation <- tibble(
          cluster_object$original_df,
          Cluster = {cluster_object$cluster %>%
              filter(id_key == input$cluster) %>%
              pull(cluster) %>% unlist()}
        )
        # generate plot
        app_helper_3d_scatter(df_plot = df_plot_scatter_observation,
                              x_axis = input$varPlotX,
                              y_axis = input$varPlotY,
                              z_axis = input$varPlotZ,
                              class_variable = 'Cluster')

      })

          # # # (AJUSTADO-OK) REACTIVE: BOX-PLOT ----
      plotBox <- reactive({
        # select the data
        df_plot_boxplot <-
          tibble(cluster_object$original_df,
                 Cluster = {cluster_object$cluster %>%
                     filter(id_key == input$cluster) %>%
                     select(cluster) %>% pull() %>% unlist()}) %>%
          mutate(Cluster = paste('cluster_', Cluster, sep = ""))

        # plot
        app_helper_boxplot(df_plot = df_plot_boxplot,
                           y_axis = input$varPlotBox,
                           class_variable = 'Cluster')
      })

          # # # (AJUSTADO-OK) REACTIVE: TABELA INFOS NÃO-PARAMÉTRICAS ABA POR CLIENTE ----
      dfNpPorCliente <- reactive({
        # select the data
        df_summary_selected_variables <-
          tibble(cluster_object$original_df,
                 Cluster = {cluster_object$cluster %>%
                     filter(id_key == input$cluster) %>%
                     pull(cluster) %>% unlist()}) %>%
          mutate(Cluster = paste('cluster_', Cluster, sep = "")) %>%
          select(Cluster, all_of(c(input$clusterX, input$clusterY, input$clusterZ)))

        # summarise
        app_helper_summary_table(df_tbl = df_summary_selected_variables,
                                 grp = 'Cluster')

      })
          # # # (AJUSTADO-OK) REACTIVE: SCATTER POR CLUSTER ----
      plotPorCluster <- reactive({
        # select the data
        df_plot_scatter_cluster <- tibble(
          cluster_object$original_df,
          Cluster = {cluster_object$cluster %>%
              filter(id_key == input$cluster) %>%
              pull(cluster) %>% unlist()}
        )
        # summarise the data
        df_plot_scatter_cluster <- df_plot_scatter_cluster %>%
          group_by(Cluster) %>%
          summarise(
            across(.cols = where(is.numeric),
                   .fns = ~mean(.x, na.rm = TRUE)),
            freq = n()
          ) %>%
          mutate(rel_freq = freq / sum(freq))

        # plot
        app_helper_3d_scatter(df_plot = df_plot_scatter_cluster,
                              x_axis = input$clusterX,
                              y_axis = input$clusterY,
                              z_axis = input$clusterZ,
                              class_variable = 'Cluster',
                              size_variable = 'rel_freq', range_sizes = c(200, 3000))
      })

          # # # REACTIVE: PLOT DA ÁRVORE DE DECISÃO ----
      tree_plot <- reactive({
        # get tree variables
        variables_tree <- cluster_object$cluster %>%
          filter(id_key == input$cluster) %>%
          pull(variables) %>% unlist() %>%
          gsub(pattern = suffix_transf, replacement = '', x = .)

        # generate data.frame for tree
        df_tree <- tibble(
          cluster_object$original_df %>% select(all_of(variables_tree)),
          Cluster = {cluster_object$cluster %>%
              filter(id_key == input$cluster) %>%
              pull(cluster) %>% unlist()}
        ) %>%
          mutate(Cluster = paste('c_', Cluster, sep = "")) %>%
          mutate(Cluster = as_factor(Cluster))

        # tree model
        cluster_tree <- ctree(Cluster ~ ., data = df_tree,
                              controls = ctree_control(maxdepth = 4))
        # plot
        plot(cluster_tree)
      })

      # # NÃO-REACTIVE ----
          # # # (AJUSTADO-OK) NÃO-REACTIVE: SCATTER + PLANO DOS CLUSTERS CANDIDATOS ----
      plotSilhueta <- app_helper_surface_3d_scatter(df = cluster_object$summary_all_candidates,
                                                    z_axis = 'mean_silh',
                                                    y_axis = 'n_variables',
                                                    x = 'k',
                                                    class_variable = 'method',
                                                    shape_variable = 'selected')

          # # # (AJUSTADO-OK) NÃO-REACTIVE: SUMÁRIO CLUSTERS ----
      dfSumario <- cluster_object$cluster %>%
        select(-cluster, -variables, -id_key) %>%
        relocate(id, .after = selected)


      # # SAÍDAS APP ----
          # # # SAÍDAS APP: NR TABELA SUMARIO ----
      output$dfSumario <- renderDataTable({
        datatable(dfSumario,extensions = 'FixedColumns',
                  options = list(
                    dom = 't',
                    scrollX = TRUE,
                    fixedColumns = TRUE
                  ))
      })
          # # # SAÍDAS APP: NR GRAFICO SILHUETA ----
      output$plotSil <- renderPlotly({
        plotSilhueta
      })

          # # # SAÍDAS APP: R TABELA NÃO-PARAMPETRICA (NÃO FORMATADA) ----
      output$dfNaoParm <- renderDataTable({
        nomesColunas <- colnames(dfNaoParm())
        datatable(dfNaoParm(),
                  rownames = FALSE, filter = 'top',
                  extensions = c('FixedHeader', 'ColReorder', 'Buttons'),
                  options = list(colReorder = TRUE,
                                 dom = 'lBfrtip',
                                 buttons = c('copy', 'csv', 'excel', 'pdf'))
        )
      })

          # # # SAÍDAS APP: R GRÁFICO CLUSTER ----
      output$plotCluster <- renderPlotly({
        plotCluster()
      })

          # # # SAÍDAS APP: TABELA INFOS NÃO-PARAMÉTRICAS ABA POR CLIENTE ----
      output$dfNpPorCliente <- renderDataTable({
        nomesColunas <- colnames(dfNpPorCliente())
        datatable(dfNpPorCliente(),
                  rownames = FALSE, filter = 'top',
                  extensions = c('FixedHeader', 'ColReorder', 'Buttons'),
                  options = list(colReorder = TRUE,
                                 dom = 'lBfrtip',
                                 buttons = c('copy', 'csv', 'excel', 'pdf'))
        )
      })
          # # # SAÍDAS APP: R GRÁFICO BOX-PLOT ----
      output$plotBox <- renderPlotly({
        plotBox()
      })
          # # # SAÍDAS APP: SCATTER POR CLUSTER ----
      output$plotPorCluster <- renderPlotly({
        plotPorCluster()
      })
          # # # SAÍDAS APP: VARIÁVEIS RECORRENTES MELHORES CLUSTERS ----
      output$dfMelhores <- renderDataTable({
        # generate frequency of tables
        df_variable_frequency <- cluster_object$cluster %>%
          select(variables) %>%
          pull() %>% unlist() %>%
          tibble(variable = .) %>%
          count(variable) %>%
          arrange(desc(n)) %>%
          # include amount of clusters and frequency it appears
          mutate(n_clusters = nrow(cluster_object$cluster))

        datatable(df_variable_frequency)

      })
          # # # SAÍDAS APP: PLOT ÁRVORE DECISÃO ----
      output$tree_plot <- renderPlot({
        tree_plot()
      })
    }
  )

  # return result
app
}
